### ISSUE TITLE
Issue with go get maxmind/mm-network-analyzer

### ISSUE THREAD

**Issue by theassyrian** [maxmind/mm-network-analyzer#2]
Line 153 : go Modified time.Now() having issue on Modified struct

func (a *analyzer) writeFile(zf *zipFile) error {
        header := &zip.FileHeader{
                Name:     zf.name,
                Method:   zip.Deflate,
                Modified: time.Now(),
        }

dbenjamin@dbenjamin ~/src/go $ go get -u github.com/maxmind/mm-network-analyzer
# github.com/maxmind/mm-network-analyzer
src/github.com/maxmind/mm-network-analyzer/main.go:153: unknown zip.FileHeader field 'Modified' in struct literal

**Comment by oschwald** [comment]
It sounds like you have an older version of `go`. This require 1.10 or 1.11. We do provide binaries on the releases page, if you prefer.

**Comment by theassyrian** [comment]
I'll try thank you
